# Spring
server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comics
    username: postgres
    password: 123
  jpa:
    generate-ddl: true

# App Properties
com:
  marvel:
    comicsproject:
      characterUri: "http://gateway.marvel.com/v1/public/characters/"
      comicUri: "http://gateway.marvel.com/v1/public/comics/"
      uploadedCharacterFolder: "/images/character/"
      uploadedComicFolder: "/images/comic/"